// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Versecue.Infrastructure.Persistence;

#nullable disable

namespace Versecue.Infrastructure.Migrations
{
    [DbContext(typeof(VersecueDbContext))]
    [Migration("20260811160836_initials")]
    partial class initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Versecue.Domain.Entities.BibleBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonicalOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Testament")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TranslationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId", "CanonicalOrder")
                        .IsUnique();

                    b.ToTable("BibleBooks", (string)null);
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("BibleChapters", (string)null);
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BibleTranslations", (string)null);
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "VerseNumber")
                        .IsUnique();

                    b.ToTable("BibleVerses", (string)null);
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleBook", b =>
                {
                    b.HasOne("Versecue.Domain.Entities.BibleTranslation", "Translation")
                        .WithMany("Books")
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleChapter", b =>
                {
                    b.HasOne("Versecue.Domain.Entities.BibleBook", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleVerse", b =>
                {
                    b.HasOne("Versecue.Domain.Entities.BibleChapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleBook", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleChapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("Versecue.Domain.Entities.BibleTranslation", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
